import { SongSuggestion } from "@/app/types/song";

export const rapAllSongs: SongSuggestion[] = [
  { title: "POMPA", artist: "PUSHER, BABA HASSAN, MERCURY" },
  { title: "BALENCI", artist: "MALIK MONTANA" },
  { title: "1998 (mam to we krwi)", artist: "BEDOES, LANEK" },
  { title: "„Tak to leciało!”", artist: "OTSOCHODZI, TACO HEMINGWAY, LOHLEQ" },
  { title: "1 na 100", artist: "White 2115, Mata, Pedro, BroJustChill" },
  { title: "1DAY IN LA", artist: "francis, bambi, OKI" },
  { title: "100 Tysięcy", artist: "Młody West" },
  { title: "Plan B", artist: "Pezet, Mata, Kaz Bałagane, Pedro, Frenkie G" },
  { title: "CASABLANCA", artist: "Sentino, BNP" },
  { title: "Kamień z serca", artist: "Bedoes 2115, Kubi Producent" },
  { title: "Plaster", artist: "Szpaku, Deemz" },
  { title: "Multisport", artist: "Kaz Bałagane, Oskar83" },
  { title: "Fluid", artist: "ReTo" },
  { title: "JEREMY SOCHAN", artist: "OKI, bvdy47" },
  { title: "STRZELAM PETEM", artist: "Guzior" },
  { title: "Futurama 3", artist: "Quebonafide" },
  { title: "Miyabi", artist: "PRO8L3M" },
  {
    title: "Młody Manson",
    artist: "Young Multi, Szpaku, Kubi Producent, Lucassi",
  },
  { title: "Atlanta", artist: "Aleshen" },
  { title: "Jagodzianki", artist: "Malik Montana, Mr. Polska" },
  { title: "Apollo", artist: "Avi, Louis Villain, Sarius" },
  { title: "Alejami gwiazd", artist: "Kaz Bałagane" },
  { title: "W GORĄCEJ WODZIE COMPANY", artist: "Bardal, rów babicze" },
  { title: "BEZ STRESU", artist: "Taco Hemingway, Rumak, Livka" },
  { title: "NIE CHCĘ WRACAĆ", artist: "Fukaj, charlie moncler, Hubert." },
  { title: "WMTB", artist: "OKI, Young Igi, Otsochodzi, OIO, @atutowy" },
  {
    title: "Nie Mam Czasu Na Wakacje",
    artist: "Żabson, Waima, Pedro, francis",
  },
  { title: "Prawie straciłem głos", artist: "Chivas" },
  { title: "Patointeligencja", artist: "Mata" },
  { title: "Zdrowie", artist: "Kizo, Janusz Walczuk" },
  {
    title: "Prometazyna",
    artist: "SB Maffija, Lanek, Beteo, Fukaj, White 2115, Pedro, francis",
  },
  { title: "Blueface", artist: "Kaz Bałagane, Młody Dron, Sher7ock" },
  { title: "Szyby", artist: "Diho, Alberto, Bibič, Josef Bratan" },
  {
    title: "PLAC TRZECH KRZYŻY",
    artist: "Taco Hemingway, @atutowy, The Returners",
  },
  { title: "Stonerki", artist: "Young Leosia, Oliwka Brazil" },
  { title: "SEXTAPE", artist: "Sobel, OKI, Deemz, Magiera, PSR" },
  { title: "RS7", artist: "ReTo, SecretRank" },
  { title: "BLUEBERRY", artist: "Guzior, Favst" },
  {
    title: "P.S.W.I.S. (DJ Eprom Remix)",
    artist: "Belmondawg, Expo 2000, DJ Eprom",
  },
  { title: "PANAMERA", artist: "Gedz, SHDØW, LOAA" },
  { title: "La Vida Loca", artist: "White 2115" },
  { title: "Pogo", artist: "Kizo, OKI" },
  { title: "BIERZ TO NA WOLNO", artist: "vkie" },
  { title: "Bellucci", artist: "Louis Villain, Guzior" },
  { title: "W DRESACH", artist: "Jan-rapowanie, Szpaku" },
  { title: "New York Freestyle", artist: "Otsochodzi, lohleq" },
  { title: "Tamagotchi", artist: "TACONAFIDE, Quebonafide, Taco Hemingway" },
  { title: "Sezon", artist: "Kabe, Opiat" },
  { title: "Midas", artist: "Sentino" },
  { title: "Papierosy_rmx", artist: "ReTo" },
  { title: "Luty", artist: "Otsochodzi" },
  { title: "Mini Man", artist: "Okekel" },
  { title: "Hit ’Em Up", artist: "Bedoes 2115" },
  { title: "Puerto Bounce", artist: "Żabson, ZetHa, Kizo" },
  { title: "Rura musi yeah", artist: "Malik Montana, Kazior" },
  { title: "All Day Everyday (Łee)", artist: "Kaz Bałagane" },
  { title: "Impreza", artist: "Sobel" },
  { title: "Comme Des Garçons", artist: "Chivas" },
  { title: "Zielona Flegma", artist: "Malik Montana, Dj.Frodo" },
  { title: "Skąd Ty To Znasz", artist: "Sentino, Diho" },
  { title: "Szaman", artist: "Paluch" },
  { title: "Gustaw", artist: "Bedoes 2115" },
  { title: "Magenta", artist: "Pezet" },
  { title: "Sorry Dolores", artist: "ReTo, Quebonafide" },
  { title: "Moment", artist: "Pusher, OSKA030, Baba Hassan" },
  { title: "AMG", artist: "Avi, Louis Villain" },
  { title: "FRISBEE", artist: "Sentino, BNP" },
  { title: "Jetlag", artist: "Malik Montana, DaChoyce, SRNO, The Plug" },
  { title: "KAMIKAZE", artist: "Mata, Khaid, Skolim" },
  { title: "ODTRUTKA", artist: "Taco Hemingway, Rumak, The Returners" },
  { title: "Mów", artist: "Otsochodzi" },
  {
    title: "Przypadkiem",
    artist: "OKI, Young Igi, Otsochodzi, OIO, Michał Anioł",
  },
  { title: "Lucky Punch", artist: "Kizo, Wac Toja" },
  { title: "Biblioteka Trap", artist: "Mata" },
  { title: "Kickdown", artist: "PRO8L3M" },
  { title: "Baciata", artist: "Malik Montana" },
  { title: "VHS", artist: "PRO8L3M" },
  { title: "Kulig", artist: "Kaz Bałagane, DMN" },
  { title: "PRZY SONECIE", artist: "Guzior" },
  { title: "911", artist: "Malik Montana, ENZO EBK" },
  { title: "Szmata", artist: "Mata" },
  { title: "Testarossa", artist: "Wiatr, Sobel, be vis" },
  {
    title: "Jesteś ładniejsza niż na zdjęciach (na zawsze)",
    artist: "Bedoes 2115, Lanek",
  },
  { title: "Monza", artist: "PRO8L3M" },
  { title: "Trójkąt Bermudzki", artist: "Sentino, Nitro, MASNY BEN, mgng" },
  { title: "Wiecznie", artist: "Sentino" },
  { title: "Szampana do ręki", artist: "Diho, Sentino" },
  { title: "Tour de France", artist: "Kabe, Favst, PLK, Gibbs" },
  { title: "Molly", artist: "PRO8L3M" },
  { title: "Kawałek nieba", artist: "Kaz Bałagane, Kukon" },
  { title: "PALMA DE MALLORCA", artist: "Mata, Żabson" },
  { title: "FRASCATI", artist: "Taco Hemingway, Zeppy Zep, Livka" },
  { title: "Grill u Gawrona", artist: "Białas, Lanek" },
  { title: "DMT", artist: "Żabson" },
  { title: "Belly Dance", artist: "Malik Montana" },
  { title: "LET IT B", artist: "bambi" },
  { title: "Rundki", artist: "Malik Montana, Diho, Alberto, Bibič" },
  { title: "Łyk i buch", artist: "SB Maffija, GOMBAO 33, Pedro, francis" },
  { title: "Driftem", artist: "Kizo, Young Igi" },
  { title: "Eldorado", artist: "Deemz, Bedoes 2115, PlanBe" },
  { title: "Zonda", artist: "Pezet" },
  {
    title: "kokaina nie pomaga ci w depresji",
    artist: "Kukon, Julia Mikuła, Ka-Meal",
  },
  { title: "Huragan", artist: "Kizo, BeMelo" },
  { title: "NICKI", artist: "Trill Pem, Wac Toja" },
  { title: "Plain Jane", artist: "Malik Montana" },
  {
    title: "Wschód (lubię zapierdalać)",
    artist: "Bedoes, Lanek, Kosa, White 2115",
  },
  { title: "Ground Zero", artist: "PRO8L3M" },
  { title: "Jungle Girl", artist: "Young Leosia, Żabson" },
  { title: "MOLO", artist: "favst, KBLEAX, Kizo, Mr. Polska" },
  { title: "Ona Mówi", artist: "730 Huncho, Kazior, Malik Montana" },
  { title: "Palo Santo", artist: "Opał, Gibbs" },
  { title: "BBS", artist: "Wiatr, Sitek" },
  { title: "DYLEMAT", artist: "Sentino" },
  { title: "GOMBAO 33", artist: "Mata, Adam33, Gombao 33, Szczepan, Wyguś" },
  { title: "Interpol", artist: "PRO8L3M" },
  { title: "Forza", artist: "Epis Dym KNF" },
  { title: "RATATATA", artist: "Sentino" },
  { title: "Ritz Carlton (Remix)", artist: "PRO8L3M, Vito Bambino" },
  { title: "Brunetki", artist: "Kaz Bałagane, Smolasty" },
  {
    title: "NA KRAŃCU ŚWIATA",
    artist: "2115, Bedoes 2115, White 2115, kuqe 2115, @atutowy",
  },
  { title: "Generał", artist: "Malik Montana, Gzuz" },
  { title: "Fitness", artist: "Kizo, Trill Pem" },
  { title: "Młody Bachor (outro)", artist: "Mata, GOMBAO 33, Deemz" },
  { title: "VOGUE", artist: "Bedoes 2115, Lanek" },
  { title: "Dior", artist: "Malik Montana" },
  { title: "Mówiłaś", artist: "Young Igi" },
  { title: "COWABONGA", artist: "Żabson" },
  { title: "Patoreakcja", artist: "Mata" },
  { title: "SIE KLEI", artist: "javier (POL)" },
  { title: "PO TEMACIE", artist: "vkie, Jacob.shawty, HUGEPAT" },
  { title: "DAM CI PORADY", artist: "vkie" },
  { title: "CAŁE LATO", artist: "Sobel" },
  {
    title: "dopóki się nie znüdzisz",
    artist: "MIÜ, Zalia, Koder, Leon Krześniak",
  },
  { title: "Polski Karnawał", artist: "Żabson, Young Igi" },
  { title: "Czarne BMW", artist: "Kukon, Magiera, Avi" },
  { title: "Dom Nad Wodą", artist: "Pezet" },
  { title: "KING", artist: "Malik Montana, Lanberry" },
  { title: "up! up! up!", artist: "Mata" },
  { title: "Hinata", artist: "Szpaku" },
  { title: "HIPNOZA", artist: "NIKOŚ (POL)" },
  {
    title: "Lawenda",
    artist:
      "SB Maffija, White 2115, Białas, Kinny Zimmer, Pedro, francis, Bedoes 2115",
  },
  {
    title: "8 kobiet - Remix",
    artist: "TACONAFIDE, Quebonafide, Taco Hemingway, Bedoes 2115",
  },
  { title: "Alicja", artist: "Szpaku" },
  { title: "Pistolet", artist: "Sentino" },
  { title: "Cichosza", artist: "Taco Hemingway, Otsochodzi, Zeppy Zep" },
  { title: "Dr. Traphouse", artist: "Kaz Bałagane, Belmondo" },
  {
    title: "ZAKOCHAŁEM SIĘ POD APTEKĄ",
    artist: "Taco Hemingway, Rumak, Livka",
  },
  { title: "Taxi", artist: "Kizo, Bletka, BeMelo, Eddie Block, Adash" },
  { title: "Wyglądam Dobrze", artist: "Fagata, Natalisa" },
  { title: "Zegar", artist: "Kaz Bałagane, Kabe, Chris Carson" },
  { title: "Blondynki", artist: "Kaz Bałagane" },
  { title: "Błoto", artist: "wane (POL)" },
  {
    title: "Fresh Prince (trill 4ever)",
    artist: "Bedoes 2115, Lanek, Malik Montana",
  },
  { title: "Pieniądze, Dziewczyny, Zwrotki", artist: "OKI, @atutowy" },
  { title: "Abu Dhabi", artist: "Baba Hassan, Oska030, Pusher, Oil Beatz" },
  { title: "Skrrrt", artist: "Young Multi, Beteo" },
  { title: "100 BPM", artist: "Kizo, @bletka" },
  { title: "Floyd Mayweather", artist: "Żabson" },
  { title: "Broly", artist: "White 2115" },
  { title: "koleżanko mojej byłej", artist: "Chivas" },
  { title: "NIE MOGĘ SPAĆ", artist: "SVM!R" },
  {
    title: "Delfin",
    artist: "Bedoes 2115, Kubi Producent, Koldi, Young Multi, Beteo",
  },
  { title: "XO", artist: "Chivas" },
  {
    title: "KETCHUP",
    artist: "2115, Bedoes 2115, Blacha 2115, White 2115, kuqe 2115",
  },
  { title: "KLAP KLAP", artist: "Dajczman" },
  { title: "Discopolo", artist: "Kizo, BeMelo, Gory" },
  { title: "Legendarne Duo", artist: "Aleshen, Yung Adisz, RYGOR, BAHsick" },
  { title: "Nie bój się bać", artist: "PRO8L3M, Anita Lipnicka, Luxon" },
  {
    title: "Czarna Perła",
    artist:
      "SB Maffija, Szpaku, Białas, Fukaj, po prostu Kajtek, White 2115, 27.Fuckdemons, Chivas, Kubi Producent",
  },
  { title: "Algeciras", artist: "Sentino" },
  { title: "Karate Kid", artist: "Białas, Lanek, Malik Montana" },
  {
    title: "DRESSCODE",
    artist: "2115, Bedoes 2115, White 2115, prześwit, Taco Hemingway",
  },
  { title: "JUŻ PÓŹNO ALE PIENIĄDZ NIE ŚPI", artist: "vkie, YPNTY" },
  { title: "SKUTE BOBO", artist: "SKUTE BOBO" },
  { title: "Speed Racing", artist: "White Widow" },
  { title: "Do Tanca", artist: "Malik Montana, Żabson, Eurosoundz" },
  { title: "Tenten", artist: "Wenext, Młody West, Okekel, wane" },
  { title: "Smoki", artist: "Bedoes 2115, Lanek" },
  { title: "Miniówa", artist: "Kukon" },
  { title: "Yabadabadoo", artist: "Salvador" },
  { title: "6.3 AMG", artist: "Malik Montana" },
  { title: "WWA Melanż", artist: "Otsochodzi, Oskar83" },
  { title: "California", artist: "White 2115" },
  { title: "Robie YEAH", artist: "Malik Montana, K Koke" },
  { title: "Lato", artist: "Sentino, CrackHouse" },
  { title: "RiRi", artist: "White 2115" },
  { title: "Złote Tarasy", artist: "Mr. Polska, Abel de Jong" },
  { title: "Robotniczy Trap", artist: "Żabson, Young Igi" },
  { title: "Icey", artist: "Żabson, Young Igi" },
  { title: "Jeżyk!", artist: "OKI, Nolyrics Beats" },
  { title: "Imago", artist: "Avi, Pezet, Jan-Rapowanie, Czarny HIFI" },
  { title: "KRESKI", artist: "Yung Adisz" },
  {
    title: "Proste fakty",
    artist:
      "SB Maffija, Bedoes 2115, White 2115, kuqe 2115, Flexxy 2115, Blacha 2115, Kubi Producent",
  },
  {
    title: "Mercedes GLE Coupé",
    artist: "Bedoes 2115, Kubi Producent, Blacha 2115, FLEXXY2115, kuqe 2115",
  },
  {
    title: "Chodzę po Luwrze",
    artist:
      "SB Maffija, Bedoes 2115, Solar, Białas, Janusz Walczuk, Pedro, francis, Jan-Rapowanie",
  },
  { title: "Drive", artist: "Gibbs, Opał, Jonatan, 4Money" },
  { title: "Polsilver", artist: "PRO8L3M" },
  { title: "Mówili", artist: "Malik Montana" },
  { title: "No to cyk", artist: "Diho" },
  { title: "BFF", artist: "bambi, Young Leosia, PG$, @atutowy" },
  { title: "ULALA", artist: "Żabson, Young Leosia, Beteo, Borucci" },
  { title: "Stan", artist: "Gibbs, Jonatan, 4Money" },
  {
    title: "Ciapakwybujany",
    artist: "GM2L, Malik Montana, Kazior, Alberto, OLEK",
  },
  { title: "MAMA POWTARZAŁA", artist: "Sobel, Deemz" },
  { title: "Sexoholik", artist: "Żabson" },
  { title: "Bogini", artist: "Quebonafide" },
  { title: "Kawior", artist: "Avi, BL Beatz" },
  {
    title: "KIEDYŚ CIĘ ZNAJDĘ (REMIX)",
    artist: "Otsochodzi, Reni Jusis, lohleq, Kusha, OKI, Young Multi",
  },
  { title: "Gozier", artist: "PLK, Paluch" },
  { title: "MY KONTRA ONI", artist: "vkie" },
  { title: "Disney", artist: "Kizo" },
  { title: "La la la (oh oh)", artist: "Mata, White 2115" },
  { title: "Nasze lato", artist: "Kizo, Wac Toja, BeMelo" },
  { title: "Pojechałem 200", artist: "Alan" },
  { title: "Bandyta", artist: "Sobel" },
  {
    title: "Amerykańskie Teledyski",
    artist: "OKI, Young Igi, Otsochodzi, OIO, Kubi Producent",
  },
  { title: "Buzi", artist: "Young Igi" },
  { title: "Nie ma", artist: "Dedis" },
  { title: "Bossman", artist: "ReTo" },
  { title: "OBOK", artist: "Żabson" },
  { title: "BMW", artist: "ReTo, Avi" },
  { title: "Crash Test", artist: "PRO8L3M" },
  { title: "ADHD", artist: "OKI, Taco Hemingway" },
  { title: "Prawy do Lewego", artist: "Mata" },
  { title: "Różowe Diamenty", artist: "Young Leosia, Deemz" },
  { title: "Gelato", artist: "Taco Hemingway, Rumak" },
  { title: "THC", artist: "Young Igi" },
  { title: "Lloret de Mar", artist: "Mata" },
  { title: "05:05", artist: "Bedoes 2115, Kubi Producent" },
  { title: "Kapitan", artist: "Wac Toja" },
  {
    title: "Parapetówa",
    artist:
      "SB Maffija, White 2115, Adi Nowak, Kacperczyk, Janusz Walczuk, Białas, Fukaj, SKUTE BOBO, Beteo, Kinny Zimmer, Solar",
  },
  { title: "Alcantara", artist: "Avi, Kukon, @atutowy" },
  { title: "Trendsetter", artist: "Kaz Bałagane" },
  {
    title: "Zapłakane Matki (Def Jam World Tour)",
    artist: "Yung Adisz, Rusina, Def Jam World Tour",
  },
  { title: "02:02", artist: "Louis Villain" },
  { title: "Numer o spodenkach krótkich", artist: "Kaz Bałagane" },
  { title: "Turkus", artist: "Kaz Bałagane" },
  { title: "Worki W Tłum", artist: "OKI, Young Igi, Otsochodzi, OIO" },
  { title: "Te Tereny", artist: "Belmondawg, Expo 2000" },
  { title: "Followup", artist: "Belmondawg, Expo 2000, Dizkret" },
  { title: "Przester", artist: "Young Leosia, bambi, PG$, francis" },
  { title: "Jungle Boyz", artist: "Malik Montana" },
  { title: "#hot16challenge2 20CALI", artist: "Kizo" },
  { title: "Justin Bieber", artist: "OKI" },
  { title: "Hotline", artist: "Waima, Mjonszu" },
  { title: "Bad Bunny", artist: "SB Maffija, Jacuś, bambi, Flory" },
  {
    title: "3 w nocy w Międzyzdrojach",
    artist:
      "SB Maffija, Mata, White 2115, Wyguś, WoLa, slowez, Mario, Pedro, wxrrior, SHDØW",
  },
  { title: "Love Story", artist: "Wac Toja, NBALVCKY" },
  { title: "SIĘ WJEŻDŻA", artist: "WŁODAR, Pedro" },
  { title: "You Cant Sit With Us", artist: "Honorata Skarbek, Malik Montana" },
  { title: "Jolie Jolie", artist: "Blacha 2115, Venom Valentino" },
  { title: "Nicea", artist: "PRO8L3M" },
  { title: "Cześć", artist: "Sokół, Sarius, Zeppy Zep" },
  { title: "LATAWCE", artist: "bambi, SecretiveSuicide" },
  { title: "Doja Cat", artist: "OKI, @atutowy" },
  { title: "Nowy biggie", artist: "Białas" },
  { title: "Labirynt", artist: "Waima" },
  { title: "Nowy sezon", artist: "Young Multi" },
  { title: "Vanitas", artist: "Aleshen" },
  { title: "RAP", artist: "Otsochodzi, lohleq" },
  { title: "RING RING", artist: "Waima, Deemz, YARSKI" },
  { title: "Wojna Totalna", artist: "Słoń, Chris Carson" },
  { title: "Księżniczki", artist: "Żabson" },
  { title: "Pogoda Drinki Plaża", artist: "Gibbs, DOPEHOUSE" },
  { title: "Niewidzialny", artist: "Gibbs" },
  { title: "Na Zawsze", artist: "White 2115" },
  { title: "Billy Kid", artist: "ReTo, Kubi Producent" },
  { title: "Młody Say10", artist: "Chivas" },
  { title: "Jakbym Miał W Ręku Klamkę", artist: "Chivas" },
  { title: "narcyz", artist: "Chivas" },
  { title: "Generacja Hip Hop", artist: "Chivas" },
  { title: "Wszokusątesuki", artist: "Belmondo, GSP, Diho, Plejer" },
  { title: "B012", artist: "Bletka" },
  { title: "champagnepapi", artist: "Otsochodzi, OKI, lohleq" },
  { title: "Vamp", artist: "Trill Pem, Worek" },
  { title: "Afryka", artist: "Szpaku, PSR" },
  {
    title: "2kcal",
    artist:
      "SB Maffija, nypel, Janusz Walczuk, Pliki, Beteo, Adi Nowak, francis",
  },
  { title: "Daj z siebie wszystko", artist: "Bob One, Bas Tajpan" },
  { title: "Pod palcami", artist: "Piotr Cartman" },
  { title: "Shakira", artist: "SB Maffija, Palar, White 2115" },
  { title: "TEN GOŚĆ", artist: "Waima, Deemz, Megot" },
  { title: "Na luzie", artist: "Paluch, Bodhi, Leśny, Dj Taek" },
  { title: "Pewex", artist: "KęKę, PSR" },
  { title: "Znachor", artist: "KęKę, Nody Beats" },
  { title: "Bąbelek", artist: "Jan-Rapowanie, Nocny" },
  { title: "Fałszywe dziwki", artist: "FIRMA" },
  { title: "GEHENNA", artist: "Gedz, Deemz, 808Bros" },
  { title: "joint i sport", artist: "kuqe 2115, francis" },
  { title: "Chwile Ulotne", artist: "Paktofonika" },
  { title: "Czerwony Rum", artist: "Słoń, Chris Carson" },
  { title: "UPS", artist: "Belmondo, GSP, Bajorson" },
  { title: "Kontrola Jakości", artist: "Paluch, Szpaku" },
  { title: "Niedostępny prod by Olek", artist: "Malik Montana, OLEK, DMN" },
  { title: "Święto ogródka", artist: "Białas, White 2115" },
  { title: "Kortyzol prod SecretRank Szwed SWD", artist: "Onar, Kabe, Kizo" },
  { title: "Cesarz", artist: "KęKę" },
  { title: "Aromatyczne Przyprawy", artist: "Żabson, Mata" },
  { title: "HOODIE", artist: "Beteo" },
  { title: "YOGA", artist: "Dreamme, Wiktor Bogdan" },
  { title: "Outside", artist: "Kartky, HVZX" },
  { title: "Vitalyi", artist: "Sentino" },
  { title: "Dana", artist: "Aleshen" },
  {
    title: "SQNHEAD",
    artist:
      "SB Maffija, Białas, Żabson, Lanek, Solar, Kinny Zimmer, Tomb, Wroobel",
  },
  { title: "Fresh", artist: "Deemz, White 2115, Donguralesko" },
  { title: "Tajne Info - Remix", artist: "Sobel, Siles" },
  { title: "Wyjebane Tak Mocno", artist: "KęKę" },
  { title: "GÓRA DÓŁ", artist: "Pako, Otsochodzi, Weely" },
  { title: "Twerk", artist: "Białas, Tomb, Wac Toja, Solar, Koldi" },
  { title: "Lyzka", artist: "Malik Montana" },
  { title: "Ibiza", artist: "Blacha 2115, Chivas" },
  { title: "Minotaur", artist: "ReTo" },
  { title: "Internaziomal", artist: "Żabson" },
  { title: "1 Moment", artist: "K2, Buka" },
  { title: "21 gramów", artist: "Zeamsone" },
  { title: "Padam Na Ryj", artist: "Sobel" },
  { title: "W Peunej Gotowości", artist: "Paktofonika" },
  { title: "chillwagon", artist: "chillwagon" },
  { title: "Modlitwa", artist: "Kaz Bałagane, Malik Montana" },
  { title: "Lecimy na koncert", artist: "Gang Albanii" },
  { title: "Dla prawdziwych dam", artist: "Gang Albanii" },
  { title: "Klub go go", artist: "Gang Albanii" },
  { title: "Mona Lisa", artist: "Malik Montana" },
  { title: "Skorpion - Remix", artist: "Malik Montana" },
  { title: "5 INFLUENCEREK", artist: "Zeamsone" },
  { title: "Safari", artist: "KęKę, Dj.Frodo" },
  { title: "Nie wal z dychy", artist: "Kaz Bałagane" },
  { title: "Pirat", artist: "Diho" },
  { title: "Priorytety", artist: "Paktofonika" },
  { title: "Rób Co Chcesz", artist: "Paktofonika" },
  { title: "Gelenda", artist: "Avi, @atutowy" },
  { title: "Pole Marysi", artist: "Ganja Mafia, Kacper HTA, Kali, PSR" },
  { title: "Orbit", artist: "Majki, Major SPZ" },
  { title: "Nawijam i smażę", artist: "Wiśnia Bakajoko" },
  { title: "Każdy blok", artist: "Paluch, PSR" },
  { title: "Hellcat Redeye", artist: "Chivas, White 2115, Szpaku" },
  {
    title: "WIĘCEJ DYMU",
    artist: "2115, Bedoes 2115, White 2115, kuqe 2115, Flexxy 2115",
  },
  { title: "Forma", artist: "Kizo" },
  { title: "Rollercoaster 2", artist: "Białas, Czerwin, Bonzo" },
  { title: "Lombard dusz", artist: "Białas, White 2115" },
  { title: "Nie bierz ze mnie przykładu", artist: "ZetHa, ReTo" },
  {
    title: "Problemy Luxusowe",
    artist: "Baba Hassan, Pusher, Oska030, @atutowy, Polski Bandyta",
  },
  { title: "Bourbon", artist: "ReTo" },
  { title: "Biggie", artist: "OKI, Young Igi, Otsochodzi, OIO, @atutowy" },
  { title: "Sam", artist: "Waima" },
  { title: "Art-B", artist: "TACONAFIDE, Quebonafide, Taco Hemingway" },
  { title: "ICE", artist: "Trill Pem, Xthauun" },
  { title: "Każdy Dzień", artist: "Kabe, Ghetto Cognac" },
  { title: "puff puff", artist: "chillwagon" },
  { title: "California", artist: "Kali, Major SPZ, Sir Mich, PlanBe" },
  { title: "Gubię kroki", artist: "SB Maffija, White 2115" },
  { title: "W Imię Ojca Trapu", artist: "Białas, Lanek" },
  {
    title: "Rolex",
    artist: "Baba Hassan, Pusher, Oska030, Newlight$, Aquila777",
  },
  {
    title: "SQP",
    artist: "Baba Hassan, Pusher, Oska030, brokeasfbeats, Polski Bandyta",
  },
  { title: "Rose Moët", artist: "Malik Montana, Diho" },
  { title: "Młody Boss", artist: "Żabson" },
  { title: "Polskie Ciężkie Trapisko", artist: "ZetHa, Żabson, Olszakumpel" },
  { title: "Papi Papi", artist: "Deemz, Beteo, Kizo, Kabe" },
  { title: "Brak snu stres i używki", artist: "Żabson, Szpaku" },
  { title: "jolka", artist: "chillwagon" },
  { title: "Plata o Plomo II", artist: "Bambo the Smuggler, Zachim, Mobbyn" },
  { title: "joker", artist: "GNG" },
  { title: "Patocelebryta", artist: "Kizo, Sergiusz" },
  { title: "Aladin", artist: "Kizo, Kabe" },
  { title: "styxbottledwater", artist: "Piotr Cartman" },
  { title: "Kwiat polskiej młodzieży", artist: "Bedoes 2115, Kubi Producent" },
  { title: "Ostatnia wieczerza", artist: "Białas, Lanek" },
  { title: "Dwutakt", artist: "Alberto, OLEK" },
  { title: "To Dopiero Poczatek", artist: "Chivas" },
  { title: "C3PO", artist: "TACONAFIDE, Quebonafide, Taco Hemingway" },
  {
    title: "Landlord",
    artist: "club2020, Otsochodzi, OKI, Young Igi, schafter, @atutowy",
  },
  { title: "Giro d’Italia", artist: "TACONAFIDE, Quebonafide, Taco Hemingway" },
  {
    title: "VISA - Remix",
    artist: "TACONAFIDE, Quebonafide, Taco Hemingway, KęKę",
  },
  { title: "Kryptowaluty", artist: "TACONAFIDE, Quebonafide, Taco Hemingway" },
  {
    title: "Nowe Szklane Domy",
    artist: "Kaz Bałagane, @atutowy, Taco Hemingway",
  },
];
