import { SongSuggestion } from "@/app/types/song";

export const klasykiAllSongs: SongSuggestion[] = [
  { title: "Otwieram wino", artist: "Sidney Polak, Pezet" },
  { title: "Sen o Warszawie", artist: "Niemen" },
  { title: "Pokolenie", artist: "Kombii" },
  { title: "Kryzysowa narzeczona", artist: "Lady Pank" },
  { title: "Dzieci wybiegły", artist: "Elektryczne Gitary" },
  { title: "Policeman", artist: "Jamal, Jambojet, USPM" },
  { title: "Byłaś dla Mnie Wszystkim", artist: "Poparzeni Kawą Trzy" },
  { title: "Jak zapomnieć", artist: "Jeden Osiem L" },
  { title: "Na co komu dziś", artist: "Lady Pank" },
  { title: "Czarny chleb i czarna kawa", artist: "Strachy Na Lachy" },
  { title: "Zanim pójdę", artist: "Happysad" },
  {
    title: "Zawsze Z Toba Chcialbym Byc... (Przez Miesiac :) )",
    artist: "Ich Troje",
  },
  { title: "Gdy nie ma dzieci", artist: "Kult" },
  { title: "Dla Mnie Masz Stajla", artist: "Trzeci Wymiar" },
  { title: "Jej czarne oczy", artist: "Ivan i Delfin" },
  { title: "Ale Wkoło Jest Wesoło", artist: "Perfect" },
  { title: "Chodź Pomaluj Mój Świat", artist: "Dwa plus Jeden" },
  { title: "Czerwone Korale", artist: "Brathanki" },
  { title: "Kawałek Do Tańca", artist: "Poparzeni Kawą Trzy" },
  { title: "Zamki na piasku", artist: "Lady Pank" },
  { title: "Wehikuł Czasu - To Byłby Cud", artist: "Dżem" },
  { title: "Zawsze tam gdzie Ty", artist: "Lady Pank" },
  { title: "Mój jest ten kawałek podłogi", artist: "Mr. Zoob" },
  { title: "Dni których nie znamy", artist: "Marek Grechuta" },
  { title: "Dzień dobry kocham Cię", artist: "Strachy Na Lachy" },
  { title: "Kocham wolność", artist: "Chłopcy z Placu Broni" },
  { title: "Mniej niż zero", artist: "Lady Pank" },
  { title: "Nie Daj Życiu Się", artist: "After Party" },
  { title: "Symetryczno-liryczna", artist: "Enej" },
  { title: "Baśka", artist: "Wilki" },
  { title: "Urke", artist: "Wilki" },
  { title: "Zodiak na melanżu", artist: "Monopol" },
  {
    title: "To my",
    artist: "Pięć Dwa Dębiec, Pięć Dwa, Hans Solo, Doniu, Ascetoholix",
  },
  { title: "Pędzą Konie", artist: "GOLEC UORKIESTRA" },
  { title: "Suczki", artist: "Ascetoholix, Doniu, Liber, Szad, Mezo" },
  { title: "Drin za Drinem", artist: "TEDE" },
  { title: "Ściernisco", artist: "GOLEC UORKIESTRA" },
  { title: "Powiedz", artist: "Ich Troje" },
  { title: "Ruda tańczy jak szalona", artist: "Czadoman" },
  { title: "Co Z Nami Będzie", artist: "Sylwia Grzeszczak, Liber" },
  { title: "Winda do Nieba", artist: "Mandaryna" },
  { title: "Chomiczówka", artist: "Sidney Polak" },
  { title: "My Cyganie", artist: "Krzysztof Krawczyk" },
  { title: "Rapapara", artist: "Łydka Grubasa" },
  { title: "Lili", artist: "Enej" },
  { title: "Agnieszka", artist: "ŁZY Adam Konkol" },
  { title: "Przekorny Los", artist: "Akcent" },
  { title: "Takie tango", artist: "Budka Suflera" },
  { title: "Czy Ten Pan I Pani", artist: "Anna Wyszkoni" },
  { title: "Kamień z Napisem Love", artist: "Enej" },
  { title: "Miłość w Zakopanem", artist: "Sławomir" },
  { title: "Przez Twe Oczy Zielone", artist: "Akcent" },
  { title: "Ona Tańczy Dla Mnie", artist: "Weekend" },
  { title: "Ale Ale Aleksandra", artist: "Andre" },
  { title: "Bałkanica", artist: "Piersi" },
  { title: "Skrzydlate Ręce", artist: "Enej" },
  { title: "Miasto budzi się", artist: "Yugopolis" },
  { title: "Zostawcie titanica", artist: "Lady Pank" },
  { title: "King Bruce Lee Karate Mistrz", artist: "Franek Kimono" },
  { title: "Hi-Fi", artist: "Wanda i Banda" },
  { title: "Cykady na Cykladach - 2011 Remaster", artist: "Maanam" },
  { title: "Ostatni raz zatańczysz ze mną", artist: "Krzysztof Krawczyk" },
  { title: "Długość dźwięku samotności", artist: "Myslovitz" },
  { title: "Makumba", artist: "Big Cyc" },
  { title: "Prawy Do Lewego", artist: "Kayah, Goran Bregović" },
  { title: "Kobiety Są Gorące", artist: "Norbi" },
  { title: "Kolorowe sny", artist: "JUST 5" },
  { title: "Każdy Facet To Świnia", artist: "Big Cyc" },
  { title: "Nie stało się nic", artist: "Robert Gawlinski" },
  { title: "Tyle słońca w całym mieście", artist: "Anna Jantar" },
  { title: "Biała armia", artist: "Bajm" },
  { title: "Kiler", artist: "Elektryczne Gitary" },
  { title: "Harley mój", artist: "Dżem" },
  { title: "Takie ładne oczy", artist: "Czerwone Gitary" },
  { title: "Biały krzyż", artist: "Czerwone Gitary" },
  { title: "Płoną góry płoną lasy", artist: "Czerwone Gitary" },
  { title: "Ciągle pada", artist: "Czerwone Gitary" },
  { title: "Dzień jeden w roku", artist: "Czerwone Gitary" },
  { title: "Rzucę ciebie, rzucę nas", artist: "Witek Muzyk Ulicy" },
];
