export interface SongSuggestion {
  title: string;
  artist: string;
}

export const allSongs: SongSuggestion[] = [
  { title: "POMPA", artist: "PUSHER, BABA HASSAN, MERCURY" },
  { title: "BALENCI", artist: "MALIK MONTANA" },
  { title: "1998 (mam to we krwi)", artist: "BEDOES, LANEK" },
  { title: "„Tak to leciało!”", artist: "OTSOCHODZI, TACO HEMINGWAY, LOHLEQ" },
  { title: "1 na 100", artist: "White 2115, Mata, Pedro, BroJustChill" },
  { title: "1DAY IN LA", artist: "francis, bambi, OKI" },
  { title: "100 Tysięcy", artist: "Młody West" },
  { title: "W GORĄCEJ WODZIE COMPANY", artist: "Bardal" },
  { title: "Luty", artist: "Otsochodzi" },
  { title: "Mini Man", artist: "Okekel" },
  { title: "Hit 'Em Up", artist: "Bedoes 2115" },
  { title: "CASABLANCA", artist: "Sentino, BNP" },
  { title: "Papierosy_rmx", artist: "ReTo" },
  { title: "Puerto Bounce", artist: "Żabson, ZetHa, Kizo" },
  { title: "STRZELAM PETEM", artist: "Guzior" },
  { title: "Rura musi yeah", artist: "Malik Montana, Kazior" },
  { title: "Bellucci", artist: "Louis Villain, Guzior" },
  { title: "All Day Everyday (Łee)", artist: "Kaz Bałagane" },
  { title: "W DRESACH", artist: "Jan-rapowanie, Szpaku" },
  { title: "Impreza", artist: "Sobel" },
  { title: "Comme Des Garçons", artist: "Chivas" },
  { title: "New York Freestyle", artist: "Otsochodzi, lohleq" },
  { title: "BIERZ TO NA WOLNO", artist: "vkie" },
  { title: "Zielona Flegma", artist: "Malik Montana, Dj.Frodo" },
  { title: "Skąd Ty To Znasz", artist: "Sentino, Diho" },
  { title: "Szaman", artist: "Paluch" },
  { title: "Gustaw", artist: "Bedoes 2115" },
  { title: "Magenta", artist: "Pezet" },
  { title: "Sorry Dolores", artist: "ReTo, Quebonafide" },
  { title: "Sezon", artist: "Kabe, Opiat" },
  { title: "Moment", artist: "Pusher, OSKA030, Baba Hassan" },
  { title: "AMG", artist: "Avi, Louis Villain" },
  { title: "FRISBEE", artist: "Sentino, BNP" },
  { title: "Jetlag", artist: "Malik Montana, DaChoyce, SRNO (Ft. The Plug)" },
  { title: "KAMIKAZE", artist: "Mata (Ft. Khaid, Skolim)" },
  { title: "ODTRUTKA", artist: "Taco Hemingway, Rumak, The Returners" },
  { title: "Mów", artist: "Otsochodzi" },
  {
    title: "Przypadkiem",
    artist: "OKI, Young Igi, Otsochodzi, OIO, Michał Anioł",
  },
  { title: "Lucky Punch", artist: "Kizo (Ft. Wac Toja)" },
  { title: "Biblioteka Trap", artist: "Mata" },
  { title: "Kickdown", artist: "PRO8L3M" },
  { title: "Baciata", artist: "Malik Montana" },
  { title: "VHS", artist: "PRO8L3M" },
  { title: "Alejami gwiazd", artist: "Kaz Bałagane" },
  { title: "Kulig", artist: "Kaz Bałagane (Ft. DMN (POL))" },
  { title: "PRZY SONECIE", artist: "Guzior" },
  { title: "911", artist: "Malik Montana, ENZO EBK" },
  { title: "Szmata", artist: "Mata" },
  { title: "Testarossa", artist: "Wiatr, Sobel, be vis" },
  {
    title: "Jesteś ładniejsza niż na zdjęciach (na zawsze)",
    artist: "Bedoes 2115, Lanek",
  },
  { title: "Monza", artist: "PRO8L3M" },
  { title: "Plan B", artist: "Pezet, Mata, Kaz Bałagane, Pedro, Frenkie G" },
  { title: "Tamagotchi", artist: "TACONAFIDE, Quebonafide, Taco Hemingway" },
  { title: "Trójkąt Bermudzki", artist: "Sentino, Nitro, MASNY BEN, mgng" },
  { title: "Wiecznie", artist: "Sentino" },
  { title: "Szampana do ręki", artist: "Diho, Sentino" },
  { title: "Tour de France", artist: "Kabe, Favst, PLK, Gibbs" },
  { title: "Molly", artist: "PRO8L3M" },
  { title: "Kawałek nieba", artist: "Kaz Bałagane (Ft. Kukon)" },
  { title: "PALMA DE MALLORCA", artist: "Mata (Ft. Żabson)" },
  { title: "FRASCATI", artist: "Taco Hemingway, Zeppy Zep, Livka" },
  { title: "Grill u Gawrona", artist: "Białas, Lanek" },
  { title: "DMT", artist: "Żabson" },
  { title: "Belly Dance", artist: "Malik Montana" },
  { title: "LET IT B", artist: "bambi" },
  {
    title: "Rundki",
    artist: "Malik Montana, Diho, Alberto, Bibič",
  },
  { title: "Łyk i buch", artist: "SB Maffija, GOMBAO 33, Pedro, francis" },
  { title: "Driftem", artist: "Kizo, Young Igi" },
  { title: "Eldorado", artist: "Deemz, Bedoes 2115, PlanBe" },
  { title: "Zonda", artist: "Pezet" },
  {
    title: "kokaina nie pomaga ci w depresji",
    artist: "Kukon, Julia Mikuła, Ka-Meal",
  },
  { title: "Huragan", artist: "Kizo, BeMelo" },
  { title: "NICKI", artist: "Trill Pem (Ft. Wac Toja)" },
  { title: "Plain Jane", artist: "Malik Montana" },
  {
    title: "Wschód (lubię zapierdalać)",
    artist: "Bedoes, Lanek, Kosa, White 2115",
  },
  { title: "Ground Zero", artist: "PRO8L3M" },
  { title: "Jungle Girl", artist: "Young Leosia (Ft. Żabson)" },
  { title: "MOLO", artist: "favst (Ft. KBLEAX, Kizo, Mr. Polska)" },
  { title: "Ona Mówi", artist: "730 Huncho (Ft. Kazior, Malik Montana)" },
  { title: "Palo Santo", artist: "Opał, Gibbs" },
  { title: "BBS", artist: "Wiatr (Ft. Sitek)" },
  { title: "BEZ STRESU", artist: "Taco Hemingway, Rumak, Livka" },
  { title: "DYLEMAT", artist: "Sentino" },
  {
    title: "GOMBAO 33",
    artist: "Mata (Ft. Adam33, Gombao 33, Szczepan, Wyguś)",
  },
  { title: "Interpol", artist: "PRO8L3M" },
  { title: "Forza", artist: "Epis Dym KNF" },
  { title: "Plaster", artist: "Szpaku, Deemz" },
  { title: "RATATATA", artist: "Sentino" },
  { title: "Ritz Carlton (Remix)", artist: "PRO8L3M (Ft. Vito Bambino)" },
  { title: "Brunetki", artist: "Kaz Bałagane (Ft. Smolasty)" },
  {
    title: "NA KRAŃCU ŚWIATA",
    artist: "2115, Bedoes 2115, White 2115, kuqe 2115, @atutowy",
  },
  { title: "Generał", artist: "Malik Montana (Ft. Gzuz)" },
  { title: "Fitness", artist: "Kizo, Trill Pem" },
  { title: "Młody Bachor (outro)", artist: "Mata, GOMBAO 33, Deemz" },
  { title: "VOGUE", artist: "Bedoes 2115, Lanek" },
  { title: "Dior", artist: "Malik Montana" },
  { title: "NIE CHCĘ WRACAĆ", artist: "Fukaj, charlie moncler (Ft. Hubert.)" },
  { title: "Mówiłaś", artist: "Young Igi" },
  { title: "COWABONGA", artist: "Żabson" },
  { title: "Patoreakcja", artist: "Mata" },
  { title: "SIE KLEI", artist: "javier (POL)" },
  { title: "PO TEMACIE", artist: "vkie, Jacob.shawty, HUGEPAT" },
  { title: "DAM CI PORADY", artist: "vkie" },
  { title: "Kamień z serca", artist: "Bedoes 2115, Kubi Producent" },
  { title: "CAŁE LATO", artist: "Sobel" },
  {
    title: "dopóki się nie znüdzisz",
    artist: "MIÜ, Zalia, Koder, Leon Krześniak",
  },
  { title: "Polski Karnawał", artist: "Żabson, Young Igi" },
  { title: "Czarne BMW", artist: "Kukon, Magiera (Ft. Avi (POL))" },
  { title: "Dom Nad Wodą", artist: "Pezet" },
  { title: "La Vida Loca", artist: "White 2115" },
  { title: "Pogo", artist: "Kizo (Ft. OKI)" },
  { title: "KING", artist: "Malik Montana, Lanberry" },
  { title: "up! up! up!", artist: "Mata" },
  { title: "Hinata", artist: "Szpaku" },
  { title: "HIPNOZA", artist: "NIKOŚ (POL)" },
  {
    title: "Lawenda",
    artist:
      "SB Maffija, White 2115, Białas, Kinny Zimmer, Pedro, francis, Bedoes 2115",
  },
  {
    title: "8 kobiet - Remix",
    artist: "TACONAFIDE, Quebonafide, Taco Hemingway, Bedoes 2115",
  },
  { title: "Alicja", artist: "Szpaku" },
  { title: "Pistolet", artist: "Sentino" },
  { title: "Fluid", artist: "ReTo" },
  { title: "Cichosza", artist: "Taco Hemingway, Otsochodzi, Zeppy Zep" },
  { title: "Dr. Traphouse", artist: "Kaz Bałagane (Ft. Belmondo)" },
  {
    title: "ZAKOCHAŁEM SIĘ POD APTEKĄ",
    artist: "Taco Hemingway, Rumak, Livka",
  },
  { title: "Taxi", artist: "Kizo, Bletka, BeMelo, Eddie Block, Adash" },
  { title: "Wyglądam Dobrze", artist: "Fagata, Natalisa" },
  { title: "Zegar", artist: "Kaz Bałagane, Kabe, Chris Carson" },
  { title: "Blondynki", artist: "Kaz Bałagane" },
  { title: "Błoto", artist: "wane (POL)" },
  {
    title: "Fresh Prince (trill 4ever)",
    artist: "Bedoes 2115, Lanek (Ft. Malik Montana)",
  },
  { title: "Pieniądze, Dziewczyny, Zwrotki", artist: "OKI, @atutowy" },
  { title: "Abu Dhabi", artist: "Baba Hassan, Oska030, Pusher, Oil Beatz" },
  {
    title: "Nie Mam Czasu Na Wakacje",
    artist: "Żabson, Waima, Pedro, francis",
  },
  { title: "Skrrrt", artist: "Young Multi (Ft. Beteo)" },
  { title: "100 BPM", artist: "Kizo, @bletka" },
  { title: "Floyd Mayweather", artist: "Żabson" },
  { title: "JEREMY SOCHAN", artist: "OKI, bvdy47" },
  { title: "Broly", artist: "White 2115" },
  { title: "koleżanko mojej byłej", artist: "Chivas" },
  { title: "NIE MOGĘ SPAĆ", artist: "SVM!R" },
  {
    title: "Delfin",
    artist: "Bedoes 2115, Kubi Producent, Koldi, Young Multi, Beteo",
  },
  { title: "XO", artist: "Chivas" },
  {
    title: "KETCHUP",
    artist: "2115, Bedoes 2115, Blacha 2115, White 2115, kuqe 2115",
  },
  { title: "KLAP KLAP", artist: "Dajczman" },
  { title: "Discopolo", artist: "Kizo, BeMelo, Gory" },
  { title: "Legendarne Duo", artist: "Aleshen, Yung Adisz, RYGOR, BAHsick" },
  { title: "Nie bój się bać", artist: "PRO8L3M, Anita Lipnicka, Luxon" },
  {
    title: "Czarna Perła",
    artist:
      "SB Maffija, Szpaku, Białas, Fukaj, po prostu Kajtek, White 2115, 27.Fuckdemons, Chivas, Kubi Producent",
  },
  { title: "Algeciras", artist: "Sentino" },
  { title: "Karate Kid", artist: "Białas, Lanek, Malik Montana" },
  { title: "Stonerki", artist: "Young Leosia (Ft. Oliwka Brazil)" },
  {
    title: "DRESSCODE",
    artist: "2115, Bedoes 2115, White 2115, prześwit, Taco Hemingway",
  },
  { title: "JUŻ PÓŹNO ALE PIENIĄDZ NIE ŚPI", artist: "vkie, YPNTY" },
  { title: "SKUTE BOBO", artist: "SKUTE BOBO" },
  { title: "SEXTAPE", artist: "Sobel, OKI, Deemz, Magiera, PSR" },
  { title: "Speed Racing", artist: "White Widow" },
  { title: "Do Tanca", artist: "Malik Montana, Żabson, Eurosoundz" },
  { title: "Tenten", artist: "Wenext (Ft. Młody West, Okekel, wane)" },
  { title: "RS7", artist: "ReTo, SecretRank" },
  { title: "Smoki", artist: "Bedoes 2115, Lanek" },
  { title: "Miniówa", artist: "Kukon" },
  { title: "Yabadabadoo", artist: "Salvador" },
  { title: "6.3 AMG", artist: "Malik Montana" },
  { title: "WWA Melanż", artist: "Otsochodzi (Ft. Oskar83)" },
  { title: "California", artist: "White 2115" },
  { title: "Robie YEAH", artist: "Malik Montana, K Koke" },
  { title: "Lato", artist: "Sentino, CrackHouse" },
  { title: "RiRi", artist: "White 2115" },
  { title: "Złote Tarasy", artist: "Mr. Polska, Abel de Jong" },
  {
    title: "Młody Manson",
    artist: "Young Multi, Szpaku, Kubi Producent, Lucassi",
  },
  { title: "Robotniczy Trap", artist: "Żabson, Young Igi" },
  { title: "Icey", artist: "Żabson, Young Igi" },
  { title: "Jeżyk!", artist: "OKI, Nolyrics Beats" },
  { title: "Miyabi", artist: "PRO8L3M" },
  { title: "Imago", artist: "Avi, Pezet, Jan-Rapowanie, Czarny HIFI" },
  { title: "KRESKI", artist: "Yung Adisz" },
  { title: "PANAMERA", artist: "Gedz, SHDØW, LOAA" },
  {
    title: "Proste fakty",
    artist:
      "SB Maffija, Bedoes 2115, White 2115, kuqe 2115, Flexxy 2115, Blacha 2115, Kubi Producent",
  },
  { title: "Atlanta", artist: "Aleshen" },
  { title: "Jagodzianki", artist: "Malik Montana, Mr. Polska" },
  { title: "Apollo", artist: "Avi, Louis Villain (Ft. Sarius)" },
  {
    title: "Mercedes GLE Coupé",
    artist:
      "Bedoes 2115, Kubi Producent (Ft. Blacha 2115, FLEXXY2115, kuqe 2115)",
  },
  {
    title: "Chodzę po Luwrze",
    artist:
      "SB Maffija, Bedoes 2115, Solar, Białas, Janusz Walczuk, Pedro, francis, Jan-Rapowanie",
  },
  { title: "Drive", artist: "Gibbs, Opał, Jonatan, 4Money" },
  { title: "Polsilver", artist: "PRO8L3M" },
  { title: "Mówili", artist: "Malik Montana" },
  { title: "No to cyk", artist: "Diho" },
  { title: "Prawie straciłem głos", artist: "Chivas" },
  { title: "BFF", artist: "bambi, Young Leosia, PG$, @atutowy" },
  { title: "ULALA", artist: "Żabson, Young Leosia, Beteo, Borucci" },
  { title: "Stan", artist: "Gibbs, Jonatan, 4Money" },
  { title: "Zdrowie", artist: "Kizo (Ft. Janusz Walczuk)" },
  {
    title: "Prometazyna",
    artist: "SB Maffija, Lanek, Beteo, Fukaj, White 2115, Pedro, francis",
  },
  { title: "Szyby", artist: "Diho, Alberto, Bibič, Josef Bratan" },
  {
    title: "Ciapakwybujany",
    artist: "GM2L, Malik Montana, Kazior, Alberto, OLEK",
  },
  { title: "MAMA POWTARZAŁA", artist: "Sobel, Deemz" },
  { title: "Sexoholik", artist: "Żabson" },
  {
    title: "PLAC TRZECH KRZYŻY",
    artist: "Taco Hemingway, @atutowy, The Returners",
  },
  { title: "Bogini", artist: "Quebonafide" },
  { title: "Kawior", artist: "Avi, BL Beatz" },
  {
    title: "KIEDYŚ CIĘ ZNAJDĘ (REMIX)",
    artist: "Otsochodzi, Reni Jusis, lohleq, Kusha (Ft. OKI, Young Multi)",
  },
  { title: "Gozier", artist: "PLK, Paluch" },
  { title: "MY KONTRA ONI", artist: "vkie" },
  { title: "Patointeligencja", artist: "Mata" },
  { title: "Disney", artist: "Kizo" },
  { title: "La la la (oh oh)", artist: "Mata (Ft. White 2115)" },
  { title: "Futurama 3", artist: "Quebonafide" },
  { title: "Nasze lato", artist: "Kizo, Wac Toja, BeMelo" },
  { title: "Pojechałem 200", artist: "Alan" },
  { title: "Bandyta", artist: "Sobel" },
  {
    title: "Amerykańskie Teledyski",
    artist: "OKI, Young Igi, Otsochodzi, OIO, Kubi Producent",
  },
  { title: "Buzi", artist: "Young Igi" },
  { title: "WMTB", artist: "OKI, Young Igi, Otsochodzi, OIO, @atutowy" },
  { title: "Nie ma", artist: "Dedis" },
  { title: "Bossman", artist: "ReTo" },
  { title: "OBOK", artist: "Żabson" },
  { title: "BMW", artist: "ReTo (Ft. Avi (POL))" },
  { title: "Crash Test", artist: "PRO8L3M" },
  { title: "BLUEBERRY", artist: "Guzior, Favst" },
  { title: "ADHD", artist: "OKI (Ft. Taco Hemingway)" },
  { title: "Prawy do Lewego", artist: "Mata" },
  { title: "Różowe Diamenty", artist: "Young Leosia, Deemz" },
  { title: "Gelato", artist: "Taco Hemingway, Rumak" },
  { title: "THC", artist: "Young Igi" },
  { title: "Blueface", artist: "Kaz Bałagane, Młody Dron, Sher7ock" },
  { title: "Lloret de Mar", artist: "Mata" },
  { title: "05:05", artist: "Bedoes 2115, Kubi Producent" },
  { title: "Kapitan", artist: "Wac Toja" },
  {
    title: "Parapetówa",
    artist:
      "SB Maffija, White 2115, Adi Nowak, Kacperczyk, Janusz Walczuk, Białas, Fukaj, SKUTE BOBO, Beteo, Kinny Zimmer, Solar",
  },
  { title: "Alcantara", artist: "Avi, Kukon, @atutowy" },
  { title: "Trendsetter", artist: "Kaz Bałagane" },
  {
    title: "Zapłakane Matki (Def Jam World Tour)",
    artist: "Yung Adisz, Rusina, Def Jam World Tour",
  },
  { title: "Multisport", artist: "Kaz Bałagane, Oskar83" },
  { title: "02:02", artist: "Louis Villain" },
  { title: "Numer o spodenkach krótkich", artist: "Kaz Bałagane" },
  { title: "Midas", artist: "Sentino" },
  { title: "Turkus", artist: "Kaz Bałagane" },
  { title: "Worki W Tłum", artist: "OKI, Young Igi, Otsochodzi, OIO" },
  { title: "P.S.W.I.S. (DJ Eprom Remix)", artist: "Belmondawg, Expo 2000, DJ Eprom" },
  { title: "Te Tereny", artist: "Belmondawg, Expo 2000" },
  { title: "Followup", artist: "Belmondawg, Expo 2000, Dizkret" },
  { title: "Przester", artist: "Young Leosia, bambi, PG$, francis" },
];
